import { GetStaticProps } from "next";
import Head from "next/head";
import prisma from "../lib/prisma";
import { Post } from "@prisma/client";
export default function Home({ post }: { post: Post }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>hello</main>
      <div>{post.title}</div>
      <div>{post.content}</div>
      <div>{post.createdAt + ""}</div>
    </>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const post = await prisma.post.findUnique({
    where: {
      id: 1,
    },
  });

  return {
    props: {
      post: JSON.parse(JSON.stringify(post)),
    },
  };
};
